INSERT INTO pokemon_types (id, title)
VALUES  (1, 'Bicho'),
        (2, 'Dragón'),
        (3, 'Hada'),
        (4, 'Fuego'),
        (5, 'Fantasma'),
        (6, 'Tierra'),
        (7, 'Normal'),
        (8, 'Psíquico'),
        (9, 'Acero'),
        (10, 'Siniestro'),
        (11, 'Eléctrico'),
        (12, 'Lucha'),
        (13, 'Volador'),
        (14, 'Planta'),
        (15, 'Hielo'),
        (16, 'Veneno'),
        (17, 'Roca'),
        (18, 'Agua');